export const CHANGE_SEARCHFIELD = "CHANGE_SEARCHFIELD";
export const FETCH_API_PEDDING = "FETCH_API_PEDDING";
export const FETCH_API_SUCCESS = "FETCH_API_SUCCESS";
export const FETCH_API_FAIL = "FETCH_API_FAIL";
